#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=journaldb
spring.data.mongodb.uri=
#spring.data.mongodb.username=XXXXX
#spring.data.mongodb.password=XXXXX
spring.data.mongodb.auto-index-creation=true
weather_api_key =