################################################## MONGO DB ########################################################
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=journaldb
spring.data.mongodb.uri=mongodb+srv://XXXXXX:XXXXXX@cluster0................................
#spring.data.mongodb.username=XXXXX
#spring.data.mongodb.password=XXXXX
spring.data.mongodb.auto-index-creation=true
################################################## TESTING ########################################################
logging.level.org.springframework.security=DEBUG
################################################## WEATHER API ########################################################
weather_api_key = XXXXXXXX
################################################## MAIL SERVICES ########################################################
spring.mail.host = smtp.gmail.com
spring.mail.port = XXXXX
spring.mail.username = XXXXXX@gmail.com
spring.mail.password =XXXX XXXX XXXX XXXX
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
################################################## REDIS ########################################################
spring.redis.host= localhost
spring.redis.port= 6379
